export const FormFieldJson = {
  category: [
    {
      type: "text",
      title: "key",
      name: "category_name",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Description",
      name: "category_description",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "file",
      title: "Image",
      name: "category_image",
      values: "",
      class: "col-span-12",
      require: false,
      multiple: false,
    },
    {
      type: "hidden",
      title: "Status",
      name: "status",
      values: 1,
      class: "col-span-3",
      require: false,
    },
    {
      type: "hidden",
      title: "Date",
      name: "created_at",
      values: new Date(),
      class: "col-span-3",
      require: false,
    },
  ],
  franchise: [
    {
      type: "text",
      title: "Name",
      name: "franchise_name",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Phone",
      name: "franchise_phone",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Email",
      name: "franchise_email",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Pincode",
      name: "franchise_pincode",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "select",
      title: "Country",
      name: "franchise_country",
      values: "",
      class: "col-span-3",
      require: false,
      server: false,
      list: [
        {
          key: "india",
          value: "India",
        },
      ],
    },
    {
      type: "select",
      title: "State",
      name: "franchise_state",
      values: "",
      class: "col-span-3",
      require: false,
      server: false,
      list: [
        {
          key: "AN",
          value: "Andaman and Nicobar Islands",
        },
        {
          key: "AP",
          value: "Andhra Pradesh",
        },
        {
          key: "AR",
          value: "Arunachal Pradesh",
        },
        {
          key: "AS",
          value: "Assam",
        },
        {
          key: "BR",
          value: "Bihar",
        },
        {
          key: "CG",
          value: "Chandigarh",
        },
        {
          key: "CH",
          value: "Chhattisgarh",
        },
        {
          key: "DH",
          value: "Dadra and Nagar Haveli",
        },
        {
          key: "DD",
          value: "Daman and Diu",
        },
        {
          key: "DL",
          value: "Delhi",
        },
        {
          key: "GA",
          value: "Goa",
        },
        {
          key: "GJ",
          value: "Gujarat",
        },
        {
          key: "HR",
          value: "Haryana",
        },
        {
          key: "HP",
          value: "Himachal Pradesh",
        },
        {
          key: "JK",
          value: "Jammu and Kashmir",
        },
        {
          key: "JH",
          value: "Jharkhand",
        },
        {
          key: "KA",
          value: "Karnataka",
        },
        {
          key: "KL",
          value: "Kerala",
        },
        {
          key: "LD",
          value: "Lakshadweep",
        },
        {
          key: "MP",
          value: "Madhya Pradesh",
        },
        {
          key: "MH",
          value: "Maharashtra",
        },
        {
          key: "MN",
          value: "Manipur",
        },
        {
          key: "ML",
          value: "Meghalaya",
        },
        {
          key: "MZ",
          value: "Mizoram",
        },
        {
          key: "NL",
          value: "Nagaland",
        },
        {
          key: "OR",
          value: "Odisha",
        },
        {
          key: "PY",
          value: "Puducherry",
        },
        {
          key: "PB",
          value: "Punjab",
        },
        {
          key: "RJ",
          value: "Rajasthan",
        },
        {
          key: "SK",
          value: "Sikkim",
        },
        {
          key: "TN",
          value: "Tamil Nadu",
        },
        {
          key: "TS",
          value: "Telangana",
        },
        {
          key: "TR",
          value: "Tripura",
        },
        {
          key: "UK",
          value: "Uttar Pradesh",
        },
        {
          key: "UP",
          value: "Uttarakhand",
        },
        {
          key: "WB",
          value: "West Bengal",
        },
      ],
    },
    {
      type: "select",
      title: "City",
      name: "franchise_city",
      values: "",
      class: "col-span-3",
      require: false,
      server: false,
      list: [
        { "value": "Mumbai", "name": "mumbai" },
        { "value": "Delhi", "name": "delhi" },
        { "value": "Bengaluru", "name": "bengaluru" },
        { "value": "Ahmedabad", "name": "ahmedabad" },
        { "value": "Hyderabad", "name": "hyderabad" },
        { "value": "Chennai", "name": "chennai" },
        { "value": "Kolkata", "name": "kolkata" },
        { "value": "Pune", "name": "pune" },
        { "value": "Jaipur", "name": "jaipur" },
        { "value": "Surat", "name": "surat" },
        { "value": "Lucknow", "name": "lucknow" },
        { "value": "Kanpur", "name": "kanpur" },
        { "value": "Nagpur", "name": "nagpur" },
        { "value": "Patna", "name": "patna" },
        { "value": "Indore", "name": "indore" },
        { "value": "Thane", "name": "thane" },
        { "value": "Bhopal", "name": "bhopal" },
        { "value": "Visakhapatnam", "name": "visakhapatnam" },
        { "value": "Vadodara", "name": "vadodara" },
        { "value": "Firozabad", "name": "firozabad" },
        { "value": "Ludhiana", "name": "ludhiana" },
        { "value": "Rajkot", "name": "rajkot" },
        { "value": "Agra", "name": "agra" },
        { "value": "Siliguri", "name": "siliguri" },
        { "value": "Nashik", "name": "nashik" },
        { "value": "Faridabad", "name": "faridabad" },
        { "value": "Patiala", "name": "patiala" },
        { "value": "Meerut", "name": "meerut" },
        { "value": "Kalyan-Dombivali", "name": "kalyan-dombivali" },
        { "value": "Vasai-Virar", "name": "vasai-virar" },
        { "value": "Varanasi", "name": "varanasi" },
        { "value": "Srinagar", "name": "srinagar" },
        { "value": "Dhanbad", "name": "dhanbad" },
        { "value": "Jodhpur", "name": "jodhpur" },
        { "value": "Amritsar", "name": "amritsar" },
        { "value": "Raipur", "name": "raipur" },
        { "value": "Allahabad", "name": "allahabad" },
        { "value": "Coimbatore", "name": "coimbatore" },
        { "value": "Jabalpur", "name": "jabalpur" },
        { "value": "Gwalior", "name": "gwalior" },
        { "value": "Vijayawada", "name": "vijayawada" },
        { "value": "Madurai", "name": "madurai" },
        { "value": "Guwahati", "name": "guwahati" },
        { "value": "Chandigarh", "name": "chandigarh" },
        { "value": "Hubli-Dharwad", "name": "hubli-dharwad" },
        { "value": "Amroha", "name": "amroha" },
        { "value": "Moradabad", "name": "moradabad" },
        { "value": "Gurgaon", "name": "gurgaon" },
        { "value": "Aligarh", "name": "aligarh" },
        { "value": "Solapur", "name": "solapur" },
        { "value": "Ranchi", "name": "ranchi" },
        { "value": "Jalandhar", "name": "jalandhar" },
        { "value": "Tiruchirappalli", "name": "tiruchirappalli" },
        { "value": "Bhubaneswar", "name": "bhubaneswar" },
        { "value": "Salem", "name": "salem" },
        { "value": "Warangal", "name": "warangal" },
        { "value": "Mira-Bhayandar", "name": "mira-bhayandar" },
        { "value": "Thiruvananthapuram", "name": "thiruvananthapuram" },
        { "value": "Bhiwandi", "name": "bhiwandi" },
        { "value": "Saharanpur", "name": "saharanpur" },
        { "value": "Guntur", "name": "guntur" },
        { "value": "Amravati", "name": "amravati" },
        { "value": "Bikaner", "name": "bikaner" },
        { "value": "Noida", "name": "noida" },
        { "value": "Jamshedpur", "name": "jamshedpur" },
        { "value": "Bhilai Nagar", "name": "bhilainagar" },
        { "value": "Cuttack", "name": "cuttack" },
        { "value": "Kochi", "name": "kochi" },
        { "value": "Udaipur", "name": "udaipur" },
        { "value": "Bhavnagar", "name": "bhavnagar" },
        { "value": "Dehradun", "name": "dehradun" },
        { "value": "Asansol", "name": "asansol" },
        { "value": "Nanded-Waghala", "name": "nanded-waghala" },
        { "value": "Ajmer", "name": "ajmer" },
        { "value": "Jamnagar", "name": "jamnagar" },
        { "value": "Ujjain", "name": "ujjain" },
        { "value": "Sangli", "name": "sangli" },
        { "value": "Loni", "name": "loni" },
        { "value": "Jhansi", "name": "jhansi" },
        { "value": "Pondicherry", "name": "pondicherry" },
        { "value": "Nellore", "name": "nellore" },
        { "value": "Jammu", "name": "jammu" },
        { "value": "Belagavi", "name": "belagavi" },
        { "value": "Raurkela", "name": "raurkela" },
        { "value": "Mangaluru", "name": "mangaluru" },
        { "value": "Tirunelveli", "name": "tirunelveli" },
        { "value": "Malegaon", "name": "malegaon" },
        { "value": "Gaya", "name": "gaya" },
        { "value": "Tiruppur", "name": "tiruppur" },
        { "value": "Davanagere", "name": "davanagere" },
        { "value": "Kozhikode", "name": "kozhikode" },
        { "value": "Akola", "name": "akola" },
        { "value": "Kurnool", "name": "kurnool" },
        { "value": "Bokaro Steel City", "name": "bokarosteel city" },
        { "value": "Rajahmundry", "name": "rajahmundry" },
        { "value": "Ballari", "name": "ballari" },
        { "value": "Agartala", "name": "agartala" },
        { "value": "Bhagalpur", "name": "bhagalpur" },
        { "value": "Latur", "name": "latur" },
        { "value": "Dhule", "name": "dhule" },
        { "value": "Korba", "name": "korba" },
        { "value": "Bhilwara", "name": "bhilwara" },
        { "value": "Brahmapur", "name": "brahmapur" },
        { "value": "Mysore", "name": "mysore" },
        { "value": "Muzaffarpur", "name": "muzaffarpur" },
        { "value": "Ahmednagar", "name": "ahmednagar" },
        { "value": "Kollam", "name": "kollam" },
        { "value": "Raghunathganj", "name": "raghunathganj" },
        { "value": "Bilaspur", "name": "bilaspur" },
        { "value": "Shahjahanpur", "name": "shahjahanpur" },
        { "value": "Thrissur", "name": "thrissur" },
        { "value": "Alwar", "name": "alwar" },
        { "value": "Kakinada", "name": "kakinada" },
        { "value": "Nizamabad", "name": "nizamabad" },
        { "value": "Sagar", "name": "sagar" },
        { "value": "Tumkur", "name": "tumkur" },
        { "value": "Hisar", "name": "hisar" },
        { "value": "Rohtak", "name": "rohtak" },
        { "value": "Panipat", "name": "panipat" },
        { "value": "Darbhanga", "name": "darbhanga" },
        { "value": "Kharagpur", "name": "kharagpur" },
        { "value": "Aizawl", "name": "aizawl" },
        { "value": "Ichalkaranji", "name": "ichalkaranji" },
        { "value": "Tirupati", "name": "tirupati" },
        { "value": "Karnal", "name": "karnal" },
        { "value": "Bathinda", "name": "bathinda" },
        { "value": "Rampur", "name": "rampur" },
        { "value": "Shivamogga", "name": "shivamogga" },
        { "value": "Ratlam", "name": "ratlam" },
        { "value": "Modinagar", "name": "modinagar" },
        { "value": "Durg", "name": "durg" },
        { "value": "Shillong", "name": "shillong" },
        { "value": "Imphal", "name": "imphal" },
        { "value": "Hapur", "name": "hapur" },
        { "value": "Ranipet", "name": "ranipet" },
        { "value": "Anantapur", "name": "anantapur" },
        { "value": "Arrah", "name": "arrah" },
        { "value": "Karimnagar", "name": "karimnagar" },
        { "value": "Parbhani", "name": "parbhani" },
        { "value": "Etawah", "name": "etawah" },
        { "value": "Bharatpur", "name": "bharatpur" },
        { "value": "Begusarai", "name": "begusarai" },
        { "value": "New Delhi", "name": "newdelhi" },
        { "value": "Chhapra", "name": "chhapra" },
        { "value": "Kadapa", "name": "kadapa" },
        { "value": "Ramagundam", "name": "ramagundam" },
        { "value": "Pali", "name": "pali" },
        { "value": "Satna", "name": "satna" },
        { "value": "Vizianagaram", "name": "vizianagaram" },
        { "value": "Katihar", "name": "katihar" },
        { "value": "Hardwar", "name": "hardwar" },
        { "value": "Sonipat", "name": "sonipat" },
        { "value": "Nagercoil", "name": "nagercoil" },
        { "value": "Thanjavur", "name": "thanjavur" },
        { "value": "Murwara (Katni)", "name": "murwara(katni)" },
        { "value": "Naihati", "name": "naihati" },
        { "value": "Sambhal", "name": "sambhal" },
        { "value": "Nadiad", "name": "nadiad" },
        { "value": "Yamunanagar", "name": "yamunanagar" },
        { "value": "English Bazar", "name": "englishbazar" },
        { "value": "Eluru", "name": "eluru" },
        { "value": "Munger", "name": "munger" },
        { "value": "Panchkula", "name": "panchkula" },
        { "value": "Raayachuru", "name": "raayachuru" },
        { "value": "Panvel", "name": "panvel" },
        { "value": "Deoghar", "name": "deoghar" },
        { "value": "Ongole", "name": "ongole" },
        { "value": "Nandyal", "name": "nandyal" },
        { "value": "Morena", "name": "morena" },
        { "value": "Bhiwani", "name": "bhiwani" },
        { "value": "Porbandar", "name": "porbandar" },
        { "value": "Palakkad", "name": "palakkad" },
        { "value": "Anand", "name": "anand" },
        { "value": "Purnia", "name": "purnia" },
        { "value": "Baharampur", "name": "baharampur" },
        { "value": "Barmer", "name": "barmer" },
        { "value": "Morvi", "name": "morvi" },
        { "value": "Orai", "name": "orai" },
        { "value": "Bahraich", "name": "bahraich" },
        { "value": "Sikar", "name": "sikar" },
        { "value": "Vellore", "name": "vellore" },
        { "value": "Singrauli", "name": "singrauli" },
        { "value": "Khammam", "name": "khammam" },
        { "value": "Mahesana", "name": "mahesana" },
        { "value": "Silchar", "name": "silchar" },
        { "value": "Sambalpur", "name": "sambalpur" },
        { "value": "Rewa", "name": "rewa" },
        { "value": "Unnao", "name": "unnao" },
        { "value": "Hugli-Chinsurah", "name": "hugli-chinsurah" },
        { "value": "Raiganj", "name": "raiganj" },
        { "value": "Phusro", "name": "phusro" },
        { "value": "Adityapur", "name": "adityapur" },
        { "value": "Alappuzha", "name": "alappuzha" },
        { "value": "Bahadurgarh", "name": "bahadurgarh" },
        { "value": "Machilipatnam", "name": "machilipatnam" },
        { "value": "Rae Bareli", "name": "raebareli" },
        { "value": "Jalpaiguri", "name": "jalpaiguri" },
        { "value": "Bharuch", "name": "bharuch" },
        { "value": "Pathankot", "name": "pathankot" },
        { "value": "Hoshiarpur", "name": "hoshiarpur" },
        { "value": "Baramula", "name": "baramula" },
        { "value": "Adoni", "name": "adoni" },
        { "value": "Jind", "name": "jind" },
        { "value": "Tonk", "name": "tonk" },
        { "value": "Tenali", "name": "tenali" },
        { "value": "Kancheepuram", "name": "kancheepuram" },
        { "value": "Vapi", "name": "vapi" },
        { "value": "Sirsa", "name": "sirsa" },
        { "value": "Navsari", "name": "navsari" },
        { "value": "Mahbubnagar", "name": "mahbubnagar" },
        { "value": "Puri", "name": "puri" },
        { "value": "Robertson Pet", "name": "robertsonpet" },
        { "value": "Erode", "name": "erode" },
        { "value": "Batala", "name": "batala" },
        { "value": "Haldwani-cum-Kathgodam", "name": "haldwani-cum-kathgodam" },
        { "value": "Vidisha", "name": "vidisha" },
        { "value": "Saharsa", "name": "saharsa" },
        { "value": "Thanesar", "name": "thanesar" },
        { "value": "Chittoor", "name": "chittoor" },
        { "value": "Veraval", "name": "veraval" },
        { "value": "Lakhimpur", "name": "lakhimpur" },
        { "value": "Sitapur", "name": "sitapur" },
        { "value": "Hindupur", "name": "hindupur" },
        { "value": "Santipur", "name": "santipur" },
        { "value": "Balurghat", "name": "balurghat" },
        { "value": "Ganjbasoda", "name": "ganjbasoda" },
        { "value": "Moga", "name": "moga" },
        { "value": "Proddatur", "name": "proddatur" },
        { "value": "Srinagar", "name": "srinagar" },
        { "value": "Medinipur", "name": "medinipur" },
        { "value": "Habra", "name": "habra" },
        { "value": "Sasaram", "name": "sasaram" },
        { "value": "Hajipur", "name": "hajipur" },
        { "value": "Bhuj", "name": "bhuj" },
        { "value": "Shivpuri", "name": "shivpuri" },
        { "value": "Ranaghat", "name": "ranaghat" },
        { "value": "Shimla", "name": "shimla" },
        { "value": "Tiruvannamalai", "name": "tiruvannamalai" },
        { "value": "Kaithal", "name": "kaithal" },
        { "value": "Rajnandgaon", "name": "rajnandgaon" },
        { "value": "Godhra", "name": "godhra" },
        { "value": "Hazaribag", "name": "hazaribag" },
        { "value": "Bhimavaram", "name": "bhimavaram" },
        { "value": "Mandsaur", "name": "mandsaur" },
        { "value": "Dibrugarh", "name": "dibrugarh" },
        { "value": "Kolar", "name": "kolar" },
        { "value": "Bankura", "name": "bankura" },
        { "value": "Mandya", "name": "mandya" },
        { "value": "Dehri-on-Sone", "name": "dehri-on-sone" },
        { "value": "Madanapalle", "name": "madanapalle" },
        { "value": "Malerkotla", "name": "malerkotla" },
        { "value": "Lalitpur", "name": "lalitpur" },
        { "value": "Bettiah", "name": "bettiah" },
        { "value": "Pollachi", "name": "pollachi" },
        { "value": "Khanna", "name": "khanna" },
        { "value": "Neemuch", "name": "neemuch" },
        { "value": "Palwal", "name": "palwal" },
        { "value": "Palanpur", "name": "palanpur" },
        { "value": "Guntakal", "name": "guntakal" },
        { "value": "Nabadwip", "name": "nabadwip" },
        { "value": "Udupi", "name": "udupi" },
        { "value": "Jagdalpur", "name": "jagdalpur" },
        { "value": "Motihari", "name": "motihari" },
        { "value": "Pilibhit", "name": "pilibhit" },
        { "value": "Dimapur", "name": "dimapur" },
        { "value": "Mohali", "name": "mohali" },
        { "value": "Sadulpur", "name": "sadulpur" },
        { "value": "Rajapalayam", "name": "rajapalayam" },
        { "value": "Dharmavaram", "name": "dharmavaram" },
        { "value": "Kashipur", "name": "kashipur" },
        { "value": "Sivakasi", "name": "sivakasi" },
        { "value": "Darjiling", "name": "darjiling" },
        { "value": "Chikkamagaluru", "name": "chikkamagaluru" },
        { "value": "Gudivada", "name": "gudivada" },
        { "value": "Baleshwar Town", "name": "baleshwartown" },
        { "value": "Mancherial", "name": "mancherial" },
        { "value": "Srikakulam", "name": "srikakulam" },
        { "value": "Adilabad", "name": "adilabad" },
        { "value": "Yavatmal", "name": "yavatmal" },
        { "value": "Barnala", "name": "barnala" },
        { "value": "Nagaon", "name": "nagaon" },
        { "value": "Narasaraopet", "name": "narasaraopet" },
        { "value": "Raigarh", "name": "raigarh" },
        { "value": "Roorkee", "name": "roorkee" },
        { "value": "Valsad", "name": "valsad" },
        { "value": "Ambikapur", "name": "ambikapur" },
        { "value": "Giridih", "name": "giridih" },
        { "value": "Chandausi", "name": "chandausi" },
        { "value": "Purulia", "name": "purulia" },
        { "value": "Patan", "name": "patan" },
        { "value": "Bagaha", "name": "bagaha" },
        { "value": "Hardoi ", "name": "hardoi" },
        { "value": "Achalpur", "name": "achalpur" },
        { "value": "Osmanabad", "name": "osmanabad" },
        { "value": "Deesa", "name": "deesa" },
        { "value": "Nandurbar", "name": "nandurbar" },
        { "value": "Azamgarh", "name": "azamgarh" },
        { "value": "Ramgarh", "name": "ramgarh" },
        { "value": "Firozpur", "name": "firozpur" },
        { "value": "Baripada Town", "name": "baripadatown" },
        { "value": "Karwar", "name": "karwar" },
        { "value": "Siwan", "name": "siwan" },
        { "value": "Rajampet", "name": "rajampet" },
        { "value": "Pudukkottai", "name": "pudukkottai" },
        { "value": "Anantnag", "name": "anantnag" },
        { "value": "Tadpatri", "name": "tadpatri" },
        { "value": "Satara", "name": "satara" },
        { "value": "Bhadrak", "name": "bhadrak" },
        { "value": "Kishanganj", "name": "kishanganj" },
        { "value": "Suryapet", "name": "suryapet" },
        { "value": "Wardha", "name": "wardha" },
        { "value": "Ranebennuru", "name": "ranebennuru" },
        { "value": "Amreli", "name": "amreli" },
        { "value": "Neyveli (TS)", "name": "neyveli(ts)" },
        { "value": "Jamalpur", "name": "jamalpur" },
        { "value": "Marmagao", "name": "marmagao" },
        { "value": "Udgir", "name": "udgir" },
        { "value": "Tadepalligudem", "name": "tadepalligudem" },
        { "value": "Nagapattinam", "name": "nagapattinam" },
        { "value": "Buxar", "name": "buxar" },
        { "value": "Aurangabad", "name": "aurangabad" },
        { "value": "Jehanabad", "name": "jehanabad" },
        { "value": "Phagwara", "name": "phagwara" },
        { "value": "Khair", "name": "khair" },
        { "value": "Sawai Madhopur", "name": "sawaimadhopur" },
        { "value": "Kapurthala", "name": "kapurthala" },
        { "value": "Chilakaluripet", "name": "chilakaluripet" },
        { "value": "Aurangabad", "name": "aurangabad" },
        { "value": "Malappuram", "name": "malappuram" },
        { "value": "Rewari", "name": "rewari" },
        { "value": "Nagaur", "name": "nagaur" },
        { "value": "Sultanpur", "name": "sultanpur" },
        { "value": "Nagda", "name": "nagda" },
        { "value": "Port Blair", "name": "portblair" },
        { "value": "Lakhisarai", "name": "lakhisarai" },
        { "value": "Panaji", "name": "panaji" },
        { "value": "Tinsukia", "name": "tinsukia" },
        { "value": "Itarsi", "name": "itarsi" },
        { "value": "Kohima", "name": "kohima" },
        { "value": "Balangir", "name": "balangir" },
        { "value": "Nawada", "name": "nawada" },
        { "value": "Jharsuguda", "name": "jharsuguda" },
        { "value": "Jagtial", "name": "jagtial" },
        { "value": "Viluppuram", "name": "viluppuram" },
        { "value": "Amalner", "name": "amalner" },
        { "value": "Zirakpur", "name": "zirakpur" },
        { "value": "Tanda", "name": "tanda" },
        { "value": "Tiruchengode", "name": "tiruchengode" },
        { "value": "Nagina", "name": "nagina" },
        { "value": "Yemmiganur", "name": "yemmiganur" },
        { "value": "Vaniyambadi", "name": "vaniyambadi" },
        { "value": "Sarni", "name": "sarni" },
        { "value": "Theni Allinagaram", "name": "theniallinagaram" },
        { "value": "Margao", "name": "margao" },
        { "value": "Akot", "name": "akot" },
        { "value": "Sehore", "name": "sehore" },
        { "value": "Mhow Cantonment", "name": "mhowcantonment" },
        { "value": "Kot Kapura", "name": "kotkapura" },
        { "value": "Makrana", "name": "makrana" },
        { "value": "Pandharpur", "name": "pandharpur" },
        { "value": "Miryalaguda", "name": "miryalaguda" },
        { "value": "Shamli", "name": "shamli" },
        { "value": "Seoni", "name": "seoni" },
        { "value": "Ranibennur", "name": "ranibennur" },
        { "value": "Kadiri", "name": "kadiri" },
        { "value": "Shrirampur", "name": "shrirampur" },
        { "value": "Rudrapur", "name": "rudrapur" },
        { "value": "Parli", "name": "parli" },
        { "value": "Najibabad", "name": "najibabad" },
        { "value": "Nirmal", "name": "nirmal" },
        { "value": "Udhagamandalam", "name": "udhagamandalam" },
        { "value": "Shikohabad", "name": "shikohabad" },
        { "value": "Jhumri Tilaiya", "name": "jhumritilaiya" },
        { "value": "Aruppukkottai", "name": "aruppukkottai" },
        { "value": "Ponnani", "name": "ponnani" },
        { "value": "Jamui", "name": "jamui" },
        { "value": "Sitamarhi", "name": "sitamarhi" },
        { "value": "Chirala", "name": "chirala" },
        { "value": "Anjar", "name": "anjar" },
        { "value": "Karaikal", "name": "karaikal" },
        { "value": "Hansi", "name": "hansi" },
        { "value": "Anakapalle", "name": "anakapalle" },
        { "value": "Mahasamund", "name": "mahasamund" },
        { "value": "Faridkot", "name": "faridkot" },
        { "value": "Saunda", "name": "saunda" },
        { "value": "Dhoraji", "name": "dhoraji" },
        { "value": "Paramakudi", "name": "paramakudi" },
        { "value": "Balaghat", "name": "balaghat" },
        { "value": "Sujangarh", "name": "sujangarh" },
        { "value": "Khambhat", "name": "khambhat" },
        { "value": "Muktsar", "name": "muktsar" },
        { "value": "Rajpura", "name": "rajpura" },
        { "value": "Kavali", "name": "kavali" },
        { "value": "Dhamtari", "name": "dhamtari" },
        { "value": "Ashok Nagar", "name": "ashoknagar" },
        { "value": "Sardarshahar", "name": "sardarshahar" },
        { "value": "Mahuva", "name": "mahuva" },
        { "value": "Bargarh", "name": "bargarh" },
        { "value": "Kamareddy", "name": "kamareddy" },
        { "value": "Sahibganj", "name": "sahibganj" },
        { "value": "Kothagudem", "name": "kothagudem" },
        { "value": "Ramanagaram", "name": "ramanagaram" },
        { "value": "Gokak", "name": "gokak" },
        { "value": "Tikamgarh", "name": "tikamgarh" },
        { "value": "Araria", "name": "araria" },
        { "value": "Rishikesh", "name": "rishikesh" },
        { "value": "Shahdol", "name": "shahdol" },
        { "value": "Medininagar (Daltonganj)", "name": "medininagar(daltonganj)" },
        { "value": "Arakkonam", "name": "arakkonam" },
        { "value": "Washim", "name": "washim" },
        { "value": "Sangrur", "name": "sangrur" },
        { "value": "Bodhan", "name": "bodhan" },
        { "value": "Fazilka", "name": "fazilka" },
        { "value": "Palacole", "name": "palacole" },
        { "value": "Keshod", "name": "keshod" },
        { "value": "Sullurpeta", "name": "sullurpeta" },
        { "value": "Wadhwan", "name": "wadhwan" },
        { "value": "Gurdaspur", "name": "gurdaspur" },
        { "value": "Vatakara", "name": "vatakara" },
        { "value": "Tura", "name": "tura" },
        { "value": "Narnaul", "name": "narnaul" },
        { "value": "Kharar", "name": "kharar" },
        { "value": "Yadgir", "name": "yadgir" },
        { "value": "Ambejogai", "name": "ambejogai" },
        { "value": "Ankleshwar", "name": "ankleshwar" },
        { "value": "Savarkundla", "name": "savarkundla" },
        { "value": "Paradip", "name": "paradip" },
        { "value": "Virudhachalam", "name": "virudhachalam" },
        { "value": "Kanhangad", "name": "kanhangad" },
        { "value": "Kadi", "name": "kadi" },
        { "value": "Srivilliputhur", "name": "srivilliputhur" },
        { "value": "Gobindgarh", "name": "gobindgarh" },
        { "value": "Tindivanam", "name": "tindivanam" },
        { "value": "Mansa", "name": "mansa" },
        { "value": "Taliparamba", "name": "taliparamba" },
        { "value": "Manmad", "name": "manmad" },
        { "value": "Tanuku", "name": "tanuku" },
        { "value": "Rayachoti", "name": "rayachoti" },
        { "value": "Virudhunagar", "name": "virudhunagar" },
        { "value": "Koyilandy", "name": "koyilandy" },
        { "value": "Jorhat", "name": "jorhat" },
        { "value": "Karur", "name": "karur" },
        { "value": "Valparai", "name": "valparai" },
        { "value": "Srikalahasti", "name": "srikalahasti" },
        { "value": "Neyyattinkara", "name": "neyyattinkara" },
        { "value": "Bapatla", "name": "bapatla" },
        { "value": "Fatehabad", "name": "fatehabad" },
        { "value": "Malout", "name": "malout" },
        { "value": "Sankarankovil", "name": "sankarankovil" },
        { "value": "Tenkasi", "name": "tenkasi" },
        { "value": "Ratnagiri", "name": "ratnagiri" },
        { "value": "Rabkavi Banhatti", "name": "rabkavibanhatti" },
        { "value": "Sikandrabad", "name": "sikandrabad" },
        { "value": "Chaibasa", "name": "chaibasa" },
        { "value": "Chirmiri", "name": "chirmiri" },
        { "value": "Palwancha", "name": "palwancha" },
        { "value": "Bhawanipatna", "name": "bhawanipatna" },
        { "value": "Kayamkulam", "name": "kayamkulam" },
        { "value": "Pithampur", "name": "pithampur" },
        { "value": "Nabha", "name": "nabha" },
        { "value": "Shahabad, Hardoi", "name": "shahabad,hardoi" },
        { "value": "Dhenkanal", "name": "dhenkanal" },
        { "value": "Uran Islampur", "name": "uranislampur" },
        { "value": "Gopalganj", "name": "gopalganj" },
        { "value": "Bongaigaon City", "name": "bongaigaoncity" },
        { "value": "Palani", "name": "palani" },
        { "value": "Pusad", "name": "pusad" },
        { "value": "Sopore", "name": "sopore" },
        { "value": "Pilkhuwa", "name": "pilkhuwa" },
        { "value": "Tarn Taran", "name": "tarntaran" },
        { "value": "Renukoot", "name": "renukoot" },
        { "value": "Mandamarri", "name": "mandamarri" },
        { "value": "Shahabad", "name": "shahabad" },
        { "value": "Barbil", "name": "barbil" },
        { "value": "Koratla", "name": "koratla" },
        { "value": "Madhubani", "name": "madhubani" },
        { "value": "Arambagh", "name": "arambagh" },
        { "value": "Gohana", "name": "gohana" },
        { "value": "Ladnu", "name": "ladnu" },
        { "value": "Pattukkottai", "name": "pattukkottai" },
        { "value": "Sirsi", "name": "sirsi" },
        { "value": "Sircilla", "name": "sircilla" },
        { "value": "Tamluk", "name": "tamluk" },
        { "value": "Jagraon", "name": "jagraon" },
        {
          "value": "AlipurdUrban Agglomerationr",
          "name": "alipurdurbanagglomerationr"
        },
        { "value": "Alirajpur", "name": "alirajpur" },
        { "value": "Tandur", "name": "tandur" },
        { "value": "Naidupet", "name": "naidupet" },
        { "value": "Tirupathur", "name": "tirupathur" },
        { "value": "Tohana", "name": "tohana" },
        { "value": "Ratangarh", "name": "ratangarh" },
        { "value": "Dhubri", "name": "dhubri" },
        { "value": "Masaurhi", "name": "masaurhi" },
        { "value": "Visnagar", "name": "visnagar" },
        { "value": "Vrindavan", "name": "vrindavan" },
        { "value": "Nokha", "name": "nokha" },
        { "value": "Nagari", "name": "nagari" },
        { "value": "Narwana", "name": "narwana" },
        { "value": "Ramanathapuram", "name": "ramanathapuram" },
        { "value": "Ujhani", "name": "ujhani" },
        { "value": "Samastipur", "name": "samastipur" },
        { "value": "Laharpur", "name": "laharpur" },
        { "value": "Sangamner", "name": "sangamner" },
        { "value": "Nimbahera", "name": "nimbahera" },
        { "value": "Siddipet", "name": "siddipet" },
        { "value": "Suri", "name": "suri" },
        { "value": "Diphu", "name": "diphu" },
        { "value": "Jhargram", "name": "jhargram" },
        { "value": "Shirpur-Warwade", "name": "shirpur-warwade" },
        { "value": "Tilhar", "name": "tilhar" },
        { "value": "Sindhnur", "name": "sindhnur" },
        { "value": "Udumalaipettai", "name": "udumalaipettai" },
        { "value": "Malkapur", "name": "malkapur" },
        { "value": "Wanaparthy", "name": "wanaparthy" },
        { "value": "Gudur", "name": "gudur" },
        { "value": "Kendujhar", "name": "kendujhar" },
        { "value": "Mandla", "name": "mandla" },
        { "value": "Mandi", "name": "mandi" },
        { "value": "Nedumangad", "name": "nedumangad" },
        { "value": "North Lakhimpur", "name": "northlakhimpur" },
        { "value": "Vinukonda", "name": "vinukonda" },
        { "value": "Tiptur", "name": "tiptur" },
        { "value": "Gobichettipalayam", "name": "gobichettipalayam" },
        { "value": "Sunabeda", "name": "sunabeda" },
        { "value": "Wani", "name": "wani" },
        { "value": "Upleta", "name": "upleta" },
        { "value": "Narasapuram", "name": "narasapuram" },
        { "value": "Nuzvid", "name": "nuzvid" },
        { "value": "Tezpur", "name": "tezpur" },
        { "value": "Una", "name": "una" },
        { "value": "Markapur", "name": "markapur" },
        { "value": "Sheopur", "name": "sheopur" },
        { "value": "Thiruvarur", "name": "thiruvarur" },
        { "value": "Sidhpur", "name": "sidhpur" },
        { "value": "Sahaswan", "name": "sahaswan" },
        { "value": "Suratgarh", "name": "suratgarh" },
        { "value": "Shajapur", "name": "shajapur" },
        { "value": "Rayagada", "name": "rayagada" },
        { "value": "Lonavla", "name": "lonavla" },
        { "value": "Ponnur", "name": "ponnur" },
        { "value": "Kagaznagar", "name": "kagaznagar" },
        { "value": "Gadwal", "name": "gadwal" },
        { "value": "Bhatapara", "name": "bhatapara" },
        { "value": "Kandukur", "name": "kandukur" },
        { "value": "Sangareddy", "name": "sangareddy" },
        { "value": "Unjha", "name": "unjha" },
        { "value": "Lunglei", "name": "lunglei" },
        { "value": "Karimganj", "name": "karimganj" },
        { "value": "Kannur", "name": "kannur" },
        { "value": "Bobbili", "name": "bobbili" },
        { "value": "Mokameh", "name": "mokameh" },
        { "value": "Talegaon Dabhade", "name": "talegaondabhade" },
        { "value": "Anjangaon", "name": "anjangaon" },
        { "value": "Mangrol", "name": "mangrol" },
        { "value": "Sunam", "name": "sunam" },
        { "value": "Gangarampur", "name": "gangarampur" },
        { "value": "Thiruvallur", "name": "thiruvallur" },
        { "value": "Tirur", "name": "tirur" },
        { "value": "Rath", "name": "rath" },
        { "value": "Jatani", "name": "jatani" },
        { "value": "Viramgam", "name": "viramgam" },
        { "value": "Rajsamand", "name": "rajsamand" },
        { "value": "Yanam", "name": "yanam" },
        { "value": "Kottayam", "name": "kottayam" },
        { "value": "Panruti", "name": "panruti" },
        { "value": "Dhuri", "name": "dhuri" },
        { "value": "Namakkal", "name": "namakkal" },
        { "value": "Kasaragod", "name": "kasaragod" },
        { "value": "Modasa", "name": "modasa" },
        { "value": "Rayadurg", "name": "rayadurg" },
        { "value": "Supaul", "name": "supaul" },
        { "value": "Kunnamkulam", "name": "kunnamkulam" },
        { "value": "Umred", "name": "umred" },
        { "value": "Bellampalle", "name": "bellampalle" },
        { "value": "Sibsagar", "name": "sibsagar" },
        { "value": "Mandi Dabwali", "name": "mandidabwali" },
        { "value": "Ottappalam", "name": "ottappalam" },
        { "value": "Dumraon", "name": "dumraon" },
        { "value": "Samalkot", "name": "samalkot" },
        { "value": "Jaggaiahpet", "name": "jaggaiahpet" },
        { "value": "Goalpara", "name": "goalpara" },
        { "value": "Tuni", "name": "tuni" },
        { "value": "Lachhmangarh", "name": "lachhmangarh" },
        { "value": "Bhongir", "name": "bhongir" },
        { "value": "Amalapuram", "name": "amalapuram" },
        { "value": "Firozpur Cantt.", "name": "firozpurcantt." },
        { "value": "Vikarabad", "name": "vikarabad" },
        { "value": "Thiruvalla", "name": "thiruvalla" },
        { "value": "Sherkot", "name": "sherkot" },
        { "value": "Palghar", "name": "palghar" },
        { "value": "Shegaon", "name": "shegaon" },
        { "value": "Jangaon", "name": "jangaon" },
        { "value": "Bheemunipatnam", "name": "bheemunipatnam" },
        { "value": "Panna", "name": "panna" },
        { "value": "Thodupuzha", "name": "thodupuzha" },
        { "value": "KathUrban Agglomeration", "name": "kathurbanagglomeration" },
        { "value": "Palitana", "name": "palitana" },
        { "value": "Arwal", "name": "arwal" },
        { "value": "Venkatagiri", "name": "venkatagiri" },
        { "value": "Kalpi", "name": "kalpi" },
        { "value": "Rajgarh (Churu)", "name": "rajgarh(churu)" },
        { "value": "Sattenapalle", "name": "sattenapalle" },
        { "value": "Arsikere", "name": "arsikere" },
        { "value": "Ozar", "name": "ozar" },
        { "value": "Thirumangalam", "name": "thirumangalam" },
        { "value": "Petlad", "name": "petlad" },
        { "value": "Nasirabad", "name": "nasirabad" },
        { "value": "Phaltan", "name": "phaltan" },
        { "value": "Rampurhat", "name": "rampurhat" },
        { "value": "Nanjangud", "name": "nanjangud" },
        { "value": "Forbesganj", "name": "forbesganj" },
        { "value": "Tundla", "name": "tundla" },
        { "value": "BhabUrban Agglomeration", "name": "bhaburbanagglomeration" },
        { "value": "Sagara", "name": "sagara" },
        { "value": "Pithapuram", "name": "pithapuram" },
        { "value": "Sira", "name": "sira" },
        { "value": "Bhadrachalam", "name": "bhadrachalam" },
        { "value": "Charkhi Dadri", "name": "charkhidadri" },
        { "value": "Chatra", "name": "chatra" },
        { "value": "Palasa Kasibugga", "name": "palasakasibugga" },
        { "value": "Nohar", "name": "nohar" },
        { "value": "Yevla", "name": "yevla" },
        { "value": "Sirhind Fatehgarh Sahib", "name": "sirhindfatehgarh sahib" },
        { "value": "Bhainsa", "name": "bhainsa" },
        { "value": "Parvathipuram", "name": "parvathipuram" },
        { "value": "Shahade", "name": "shahade" },
        { "value": "Chalakudy", "name": "chalakudy" },
        { "value": "Narkatiaganj", "name": "narkatiaganj" },
        { "value": "Kapadvanj", "name": "kapadvanj" },
        { "value": "Macherla", "name": "macherla" },
        { "value": "Raghogarh-Vijaypur", "name": "raghogarh-vijaypur" },
        { "value": "Rupnagar", "name": "rupnagar" },
        { "value": "Naugachhia", "name": "naugachhia" },
        { "value": "Sendhwa", "name": "sendhwa" },
        { "value": "Byasanagar", "name": "byasanagar" },
        { "value": "Sandila", "name": "sandila" },
        { "value": "Gooty", "name": "gooty" },
        { "value": "Salur", "name": "salur" },
        { "value": "Nanpara", "name": "nanpara" },
        { "value": "Sardhana", "name": "sardhana" },
        { "value": "Vita", "name": "vita" },
        { "value": "Gumia", "name": "gumia" },
        { "value": "Puttur", "name": "puttur" },
        { "value": "Jalandhar Cantt.", "name": "jalandharcantt." },
        { "value": "Nehtaur", "name": "nehtaur" },
        { "value": "Changanassery", "name": "changanassery" },
        { "value": "Mandapeta", "name": "mandapeta" },
        { "value": "Dumka", "name": "dumka" },
        { "value": "Seohara", "name": "seohara" },
        { "value": "Umarkhed", "name": "umarkhed" },
        { "value": "Madhupur", "name": "madhupur" },
        { "value": "Vikramasingapuram", "name": "vikramasingapuram" },
        { "value": "Punalur", "name": "punalur" },
        { "value": "Kendrapara", "name": "kendrapara" },
        { "value": "Sihor", "name": "sihor" },
        { "value": "Nellikuppam", "name": "nellikuppam" },
        { "value": "Samana", "name": "samana" },
        { "value": "Warora", "name": "warora" },
        { "value": "Nilambur", "name": "nilambur" },
        { "value": "Rasipuram", "name": "rasipuram" },
        { "value": "Ramnagar", "name": "ramnagar" },
        { "value": "Jammalamadugu", "name": "jammalamadugu" },
        { "value": "Nawanshahr", "name": "nawanshahr" },
        { "value": "Thoubal", "name": "thoubal" },
        { "value": "Athni", "name": "athni" },
        { "value": "Cherthala", "name": "cherthala" },
        { "value": "Sidhi", "name": "sidhi" },
        { "value": "Farooqnagar", "name": "farooqnagar" },
        { "value": "Peddapuram", "name": "peddapuram" },
        { "value": "Chirkunda", "name": "chirkunda" },
        { "value": "Pachora", "name": "pachora" },
        { "value": "Madhepura", "name": "madhepura" },
        { "value": "Pithoragarh", "name": "pithoragarh" },
        { "value": "Tumsar", "name": "tumsar" },
        { "value": "Phalodi", "name": "phalodi" },
        { "value": "Tiruttani", "name": "tiruttani" },
        { "value": "Rampura Phul", "name": "rampuraphul" },
        { "value": "Perinthalmanna", "name": "perinthalmanna" },
        { "value": "Padrauna", "name": "padrauna" },
        { "value": "Pipariya", "name": "pipariya" },
        { "value": "Dalli-Rajhara", "name": "dalli-rajhara" },
        { "value": "Punganur", "name": "punganur" },
        { "value": "Mattannur", "name": "mattannur" },
        { "value": "Mathura", "name": "mathura" },
        { "value": "Thakurdwara", "name": "thakurdwara" },
        { "value": "Nandivaram-Guduvancheri", "name": "nandivaram-guduvancheri" },
        { "value": "Mulbagal", "name": "mulbagal" },
        { "value": "Manjlegaon", "name": "manjlegaon" },
        { "value": "Wankaner", "name": "wankaner" },
        { "value": "Sillod", "name": "sillod" },
        { "value": "Nidadavole", "name": "nidadavole" },
        { "value": "Surapura", "name": "surapura" },
        { "value": "Rajagangapur", "name": "rajagangapur" },
        { "value": "Sheikhpura", "name": "sheikhpura" },
        { "value": "Parlakhemundi", "name": "parlakhemundi" },
        { "value": "Kalimpong", "name": "kalimpong" },
        { "value": "Siruguppa", "name": "siruguppa" },
        { "value": "Arvi", "name": "arvi" },
        { "value": "Limbdi", "name": "limbdi" },
        { "value": "Barpeta", "name": "barpeta" },
        { "value": "Manglaur", "name": "manglaur" },
        { "value": "Repalle", "name": "repalle" },
        { "value": "Mudhol", "name": "mudhol" },
        { "value": "Shujalpur", "name": "shujalpur" },
        { "value": "Mandvi", "name": "mandvi" },
        { "value": "Thangadh", "name": "thangadh" },
        { "value": "Sironj", "name": "sironj" },
        { "value": "Nandura", "name": "nandura" },
        { "value": "Shoranur", "name": "shoranur" },
        { "value": "Nathdwara", "name": "nathdwara" },
        { "value": "Periyakulam", "name": "periyakulam" },
        { "value": "Sultanganj", "name": "sultanganj" },
        { "value": "Medak", "name": "medak" },
        { "value": "Narayanpet", "name": "narayanpet" },
        { "value": "Raxaul Bazar", "name": "raxaulbazar" },
        { "value": "Rajauri", "name": "rajauri" },
        { "value": "Pernampattu", "name": "pernampattu" },
        { "value": "Nainital", "name": "nainital" },
        { "value": "Ramachandrapuram", "name": "ramachandrapuram" },
        { "value": "Vaijapur", "name": "vaijapur" },
        { "value": "Nangal", "name": "nangal" },
        { "value": "Sidlaghatta", "name": "sidlaghatta" },
        { "value": "Punch", "name": "punch" },
        { "value": "Pandhurna", "name": "pandhurna" },
        { "value": "Wadgaon Road", "name": "wadgaonroad" },
        { "value": "Talcher", "name": "talcher" },
        { "value": "Varkala", "name": "varkala" },
        { "value": "Pilani", "name": "pilani" },
        { "value": "Nowgong", "name": "nowgong" },
        { "value": "Naila Janjgir", "name": "nailajanjgir" },
        { "value": "Mapusa", "name": "mapusa" },
        { "value": "Vellakoil", "name": "vellakoil" },
        { "value": "Merta City", "name": "mertacity" },
        { "value": "Sivaganga", "name": "sivaganga" },
        { "value": "Mandideep", "name": "mandideep" },
        { "value": "Sailu", "name": "sailu" },
        { "value": "Vyara", "name": "vyara" },
        { "value": "Kovvur", "name": "kovvur" },
        { "value": "Vadalur", "name": "vadalur" },
        { "value": "Nawabganj", "name": "nawabganj" },
        { "value": "Padra", "name": "padra" },
        { "value": "Sainthia", "name": "sainthia" },
        { "value": "Siana", "name": "siana" },
        { "value": "Shahpur", "name": "shahpur" },
        { "value": "Sojat", "name": "sojat" },
        { "value": "Noorpur", "name": "noorpur" },
        { "value": "Paravoor", "name": "paravoor" },
        { "value": "Murtijapur", "name": "murtijapur" },
        { "value": "Ramnagar", "name": "ramnagar" },
        { "value": "Sundargarh", "name": "sundargarh" },
        { "value": "Taki", "name": "taki" },
        { "value": "Saundatti-Yellamma", "name": "saundatti-yellamma" },
        { "value": "Pathanamthitta", "name": "pathanamthitta" },
        { "value": "Wadi", "name": "wadi" },
        { "value": "Rameshwaram", "name": "rameshwaram" },
        { "value": "Tasgaon", "name": "tasgaon" },
        { "value": "Sikandra Rao", "name": "sikandrarao" },
        { "value": "Sihora", "name": "sihora" },
        { "value": "Tiruvethipuram", "name": "tiruvethipuram" },
        { "value": "Tiruvuru", "name": "tiruvuru" },
        { "value": "Mehkar", "name": "mehkar" },
        { "value": "Peringathur", "name": "peringathur" },
        { "value": "Perambalur", "name": "perambalur" },
        { "value": "Manvi", "name": "manvi" },
        { "value": "Zunheboto", "name": "zunheboto" },
        { "value": "Mahnar Bazar", "name": "mahnarbazar" },
        { "value": "Attingal", "name": "attingal" },
        { "value": "Shahbad", "name": "shahbad" },
        { "value": "Puranpur", "name": "puranpur" },
        { "value": "Nelamangala", "name": "nelamangala" },
        { "value": "Nakodar", "name": "nakodar" },
        { "value": "Lunawada", "name": "lunawada" },
        { "value": "Murshidabad", "name": "murshidabad" },
        { "value": "Mahe", "name": "mahe" },
        { "value": "Lanka", "name": "lanka" },
        { "value": "Rudauli", "name": "rudauli" },
        { "value": "Tuensang", "name": "tuensang" },
        { "value": "Lakshmeshwar", "name": "lakshmeshwar" },
        { "value": "Zira", "name": "zira" },
        { "value": "Yawal", "name": "yawal" },
        { "value": "Thana Bhawan", "name": "thanabhawan" },
        { "value": "Ramdurg", "name": "ramdurg" },
        { "value": "Pulgaon", "name": "pulgaon" },
        { "value": "Sadasivpet", "name": "sadasivpet" },
        { "value": "Nargund", "name": "nargund" },
        { "value": "Neem-Ka-Thana", "name": "neem-ka-thana" },
        { "value": "Memari", "name": "memari" },
        { "value": "Nilanga", "name": "nilanga" },
        { "value": "Naharlagun", "name": "naharlagun" },
        { "value": "Pakaur", "name": "pakaur" },
        { "value": "Wai", "name": "wai" },
        { "value": "Tarikere", "name": "tarikere" },
        { "value": "Malavalli", "name": "malavalli" },
        { "value": "Raisen", "name": "raisen" },
        { "value": "Lahar", "name": "lahar" },
        { "value": "Uravakonda", "name": "uravakonda" },
        { "value": "Savanur", "name": "savanur" },
        { "value": "Sirohi", "name": "sirohi" },
        { "value": "Udhampur", "name": "udhampur" },
        { "value": "Umarga", "name": "umarga" },
        { "value": "Pratapgarh", "name": "pratapgarh" },
        { "value": "Lingsugur", "name": "lingsugur" },
        { "value": "Usilampatti", "name": "usilampatti" },
        { "value": "Palia Kalan", "name": "paliakalan" },
        { "value": "Wokha", "name": "wokha" },
        { "value": "Rajpipla", "name": "rajpipla" },
        { "value": "Vijayapura", "name": "vijayapura" },
        { "value": "Rawatbhata", "name": "rawatbhata" },
        { "value": "Sangaria", "name": "sangaria" },
        { "value": "Paithan", "name": "paithan" },
        { "value": "Rahuri", "name": "rahuri" },
        { "value": "Patti", "name": "patti" },
        { "value": "Zaidpur", "name": "zaidpur" },
        { "value": "Lalsot", "name": "lalsot" },
        { "value": "Maihar", "name": "maihar" },
        { "value": "Vedaranyam", "name": "vedaranyam" },
        { "value": "Nawapur", "name": "nawapur" },
        { "value": "Solan", "name": "solan" },
        { "value": "Vapi", "name": "vapi" },
        { "value": "Sanawad", "name": "sanawad" },
        { "value": "Warisaliganj", "name": "warisaliganj" },
        { "value": "Revelganj", "name": "revelganj" },
        { "value": "Sabalgarh", "name": "sabalgarh" },
        { "value": "Tuljapur", "name": "tuljapur" },
        { "value": "Simdega", "name": "simdega" },
        { "value": "Musabani", "name": "musabani" },
        { "value": "Kodungallur", "name": "kodungallur" },
        { "value": "Phulabani", "name": "phulabani" },
        { "value": "Umreth", "name": "umreth" },
        { "value": "Narsipatnam", "name": "narsipatnam" },
        { "value": "Nautanwa", "name": "nautanwa" },
        { "value": "Rajgir", "name": "rajgir" },
        { "value": "Yellandu", "name": "yellandu" },
        { "value": "Sathyamangalam", "name": "sathyamangalam" },
        { "value": "Pilibanga", "name": "pilibanga" },
        { "value": "Morshi", "name": "morshi" },
        { "value": "Pehowa", "name": "pehowa" },
        { "value": "Sonepur", "name": "sonepur" },
        { "value": "Pappinisseri", "name": "pappinisseri" },
        { "value": "Zamania", "name": "zamania" },
        { "value": "Mihijam", "name": "mihijam" },
        { "value": "Purna", "name": "purna" },
        { "value": "Puliyankudi", "name": "puliyankudi" },
        { "value": "Shikarpur, Bulandshahr", "name": "shikarpur,bulandshahr" },
        { "value": "Umaria", "name": "umaria" },
        { "value": "Porsa", "name": "porsa" },
        { "value": "Naugawan Sadat", "name": "naugawansadat" },
        { "value": "Fatehpur Sikri", "name": "fatehpursikri" },
        { "value": "Manuguru", "name": "manuguru" },
        { "value": "Udaipur", "name": "udaipur" },
        { "value": "Pipar City", "name": "piparcity" },
        { "value": "Pattamundai", "name": "pattamundai" },
        { "value": "Nanjikottai", "name": "nanjikottai" },
        { "value": "Taranagar", "name": "taranagar" },
        { "value": "Yerraguntla", "name": "yerraguntla" },
        { "value": "Satana", "name": "satana" },
        { "value": "Sherghati", "name": "sherghati" },
        { "value": "Sankeshwara", "name": "sankeshwara" },
        { "value": "Madikeri", "name": "madikeri" },
        { "value": "Thuraiyur", "name": "thuraiyur" },
        { "value": "Sanand", "name": "sanand" },
        { "value": "Rajula", "name": "rajula" },
        { "value": "Kyathampalle", "name": "kyathampalle" },
        { "value": "Shahabad, Rampur", "name": "shahabad,rampur" },
        { "value": "Tilda Newra", "name": "tildanewra" },
        { "value": "Narsinghgarh", "name": "narsinghgarh" },
        { "value": "Chittur-Thathamangalam", "name": "chittur-thathamangalam" },
        { "value": "Malaj Khand", "name": "malajkhand" },
        { "value": "Sarangpur", "name": "sarangpur" },
        { "value": "Robertsganj", "name": "robertsganj" },
        { "value": "Sirkali", "name": "sirkali" },
        { "value": "Radhanpur", "name": "radhanpur" },
        { "value": "Tiruchendur", "name": "tiruchendur" },
        { "value": "Utraula", "name": "utraula" },
        { "value": "Patratu", "name": "patratu" },
        { "value": "Vijainagar, Ajmer", "name": "vijainagar,ajmer" },
        { "value": "Periyasemur", "name": "periyasemur" },
        { "value": "Pathri", "name": "pathri" },
        { "value": "Sadabad", "name": "sadabad" },
        { "value": "Talikota", "name": "talikota" },
        { "value": "Sinnar", "name": "sinnar" },
        { "value": "Mungeli", "name": "mungeli" },
        { "value": "Sedam", "name": "sedam" },
        { "value": "Shikaripur", "name": "shikaripur" },
        { "value": "Sumerpur", "name": "sumerpur" },
        { "value": "Sattur", "name": "sattur" },
        { "value": "Sugauli", "name": "sugauli" },
        { "value": "Lumding", "name": "lumding" },
        { "value": "Vandavasi", "name": "vandavasi" },
        { "value": "Titlagarh", "name": "titlagarh" },
        { "value": "Uchgaon", "name": "uchgaon" },
        { "value": "Mokokchung", "name": "mokokchung" },
        { "value": "Paschim Punropara", "name": "paschimpunropara" },
        { "value": "Sagwara", "name": "sagwara" },
        { "value": "Ramganj Mandi", "name": "ramganjmandi" },
        { "value": "Tarakeswar", "name": "tarakeswar" },
        { "value": "Mahalingapura", "name": "mahalingapura" },
        { "value": "Dharmanagar", "name": "dharmanagar" },
        { "value": "Mahemdabad", "name": "mahemdabad" },
        { "value": "Manendragarh", "name": "manendragarh" },
        { "value": "Uran", "name": "uran" },
        { "value": "Tharamangalam", "name": "tharamangalam" },
        { "value": "Tirukkoyilur", "name": "tirukkoyilur" },
        { "value": "Pen", "name": "pen" },
        { "value": "Makhdumpur", "name": "makhdumpur" },
        { "value": "Maner", "name": "maner" },
        { "value": "Oddanchatram", "name": "oddanchatram" },
        { "value": "Palladam", "name": "palladam" },
        { "value": "Mundi", "name": "mundi" },
        { "value": "Nabarangapur", "name": "nabarangapur" },
        { "value": "Mudalagi", "name": "mudalagi" },
        { "value": "Samalkha", "name": "samalkha" },
        { "value": "Nepanagar", "name": "nepanagar" },
        { "value": "Karjat", "name": "karjat" },
        { "value": "Ranavav", "name": "ranavav" },
        { "value": "Pedana", "name": "pedana" },
        { "value": "Pinjore", "name": "pinjore" },
        { "value": "Lakheri", "name": "lakheri" },
        { "value": "Pasan", "name": "pasan" },
        { "value": "Puttur", "name": "puttur" },
        { "value": "Vadakkuvalliyur", "name": "vadakkuvalliyur" },
        { "value": "Tirukalukundram", "name": "tirukalukundram" },
        { "value": "Mahidpur", "name": "mahidpur" },
        { "value": "Mussoorie", "name": "mussoorie" },
        { "value": "Muvattupuzha", "name": "muvattupuzha" },
        { "value": "Rasra", "name": "rasra" },
        { "value": "Udaipurwati", "name": "udaipurwati" },
        { "value": "Manwath", "name": "manwath" },
        { "value": "Adoor", "name": "adoor" },
        { "value": "Uthamapalayam", "name": "uthamapalayam" },
        { "value": "Partur", "name": "partur" },
        { "value": "Nahan", "name": "nahan" },
        { "value": "Ladwa", "name": "ladwa" },
        { "value": "Mankachar", "name": "mankachar" },
        { "value": "Nongstoin", "name": "nongstoin" },
        { "value": "Losal", "name": "losal" },
        { "value": "Sri Madhopur", "name": "srimadhopur" },
        { "value": "Ramngarh", "name": "ramngarh" },
        { "value": "Mavelikkara", "name": "mavelikkara" },
        { "value": "Rawatsar", "name": "rawatsar" },
        { "value": "Rajakhera", "name": "rajakhera" },
        { "value": "Lar", "name": "lar" },
        { "value": "Lal Gopalganj Nindaura", "name": "lalgopalganj nindaura" },
        { "value": "Muddebihal", "name": "muddebihal" },
        { "value": "Sirsaganj", "name": "sirsaganj" },
        { "value": "Shahpura", "name": "shahpura" },
        { "value": "Surandai", "name": "surandai" },
        { "value": "Sangole", "name": "sangole" },
        { "value": "Pavagada", "name": "pavagada" },
        { "value": "Tharad", "name": "tharad" },
        { "value": "Mansa", "name": "mansa" },
        { "value": "Umbergaon", "name": "umbergaon" },
        { "value": "Mavoor", "name": "mavoor" },
        { "value": "Nalbari", "name": "nalbari" },
        { "value": "Talaja", "name": "talaja" },
        { "value": "Malur", "name": "malur" },
        { "value": "Mangrulpir", "name": "mangrulpir" },
        { "value": "Soro", "name": "soro" },
        { "value": "Shahpura", "name": "shahpura" },
        { "value": "Vadnagar", "name": "vadnagar" },
        { "value": "Raisinghnagar", "name": "raisinghnagar" },
        { "value": "Sindhagi", "name": "sindhagi" },
        { "value": "Sanduru", "name": "sanduru" },
        { "value": "Sohna", "name": "sohna" },
        { "value": "Manavadar", "name": "manavadar" },
        { "value": "Pihani", "name": "pihani" },
        { "value": "Safidon", "name": "safidon" },
        { "value": "Risod", "name": "risod" },
        { "value": "Rosera", "name": "rosera" },
        { "value": "Sankari", "name": "sankari" },
        { "value": "Malpura", "name": "malpura" },
        { "value": "Sonamukhi", "name": "sonamukhi" },
        { "value": "Shamsabad, Agra", "name": "shamsabad,agra" },
        { "value": "Nokha", "name": "nokha" },
        { "value": "PandUrban Agglomeration", "name": "pandurbanagglomeration" },
        { "value": "Mainaguri", "name": "mainaguri" },
        { "value": "Afzalpur", "name": "afzalpur" },
        { "value": "Shirur", "name": "shirur" },
        { "value": "Salaya", "name": "salaya" },
        { "value": "Shenkottai", "name": "shenkottai" },
        { "value": "Pratapgarh", "name": "pratapgarh" },
        { "value": "Vadipatti", "name": "vadipatti" },
        { "value": "Nagarkurnool", "name": "nagarkurnool" },
        { "value": "Savner", "name": "savner" },
        { "value": "Sasvad", "name": "sasvad" },
        { "value": "Rudrapur", "name": "rudrapur" },
        { "value": "Soron", "name": "soron" },
        { "value": "Sholingur", "name": "sholingur" },
        { "value": "Pandharkaoda", "name": "pandharkaoda" },
        { "value": "Perumbavoor", "name": "perumbavoor" },
        { "value": "Maddur", "name": "maddur" },
        { "value": "Nadbai", "name": "nadbai" },
        { "value": "Talode", "name": "talode" },
        { "value": "Shrigonda", "name": "shrigonda" },
        { "value": "Madhugiri", "name": "madhugiri" },
        { "value": "Tekkalakote", "name": "tekkalakote" },
        { "value": "Seoni-Malwa", "name": "seoni-malwa" },
        { "value": "Shirdi", "name": "shirdi" },
        { "value": "SUrban Agglomerationr", "name": "surbanagglomerationr" },
        { "value": "Terdal", "name": "terdal" },
        { "value": "Raver", "name": "raver" },
        { "value": "Tirupathur", "name": "tirupathur" },
        { "value": "Taraori", "name": "taraori" },
        { "value": "Mukhed", "name": "mukhed" },
        { "value": "Manachanallur", "name": "manachanallur" },
        { "value": "Rehli", "name": "rehli" },
        { "value": "Sanchore", "name": "sanchore" },
        { "value": "Rajura", "name": "rajura" },
        { "value": "Piro", "name": "piro" },
        { "value": "Mudabidri", "name": "mudabidri" },
        { "value": "Vadgaon Kasba", "name": "vadgaonkasba" },
        { "value": "Nagar", "name": "nagar" },
        { "value": "Vijapur", "name": "vijapur" },
        { "value": "Viswanatham", "name": "viswanatham" },
        { "value": "Polur", "name": "polur" },
        { "value": "Panagudi", "name": "panagudi" },
        { "value": "Manawar", "name": "manawar" },
        { "value": "Tehri", "name": "tehri" },
        { "value": "Samdhan", "name": "samdhan" },
        { "value": "Pardi", "name": "pardi" },
        { "value": "Rahatgarh", "name": "rahatgarh" },
        { "value": "Panagar", "name": "panagar" },
        { "value": "Uthiramerur", "name": "uthiramerur" },
        { "value": "Tirora", "name": "tirora" },
        { "value": "Rangia", "name": "rangia" },
        { "value": "Sahjanwa", "name": "sahjanwa" },
        { "value": "Wara Seoni", "name": "waraseoni" },
        { "value": "Magadi", "name": "magadi" },
        { "value": "Rajgarh (Alwar)", "name": "rajgarh(alwar)" },
        { "value": "Rafiganj", "name": "rafiganj" },
        { "value": "Tarana", "name": "tarana" },
        { "value": "Rampur Maniharan", "name": "rampurmaniharan" },
        { "value": "Sheoganj", "name": "sheoganj" },
        { "value": "Raikot", "name": "raikot" },
        { "value": "Pauri", "name": "pauri" },
        { "value": "Sumerpur", "name": "sumerpur" },
        { "value": "Navalgund", "name": "navalgund" },
        { "value": "Shahganj", "name": "shahganj" },
        { "value": "Marhaura", "name": "marhaura" },
        { "value": "Tulsipur", "name": "tulsipur" },
        { "value": "Sadri", "name": "sadri" },
        { "value": "Thiruthuraipoondi", "name": "thiruthuraipoondi" },
        { "value": "Shiggaon", "name": "shiggaon" },
        { "value": "Pallapatti", "name": "pallapatti" },
        { "value": "Mahendragarh", "name": "mahendragarh" },
        { "value": "Sausar", "name": "sausar" },
        { "value": "Ponneri", "name": "ponneri" },
        { "value": "Mahad", "name": "mahad" },
        { "value": "Lohardaga", "name": "lohardaga" },
        { "value": "Tirwaganj", "name": "tirwaganj" },
        { "value": "Margherita", "name": "margherita" },
        { "value": "Sundarnagar", "name": "sundarnagar" },
        { "value": "Rajgarh", "name": "rajgarh" },
        { "value": "Mangaldoi", "name": "mangaldoi" },
        { "value": "Renigunta", "name": "renigunta" },
        { "value": "Longowal", "name": "longowal" },
        { "value": "Ratia", "name": "ratia" },
        { "value": "Lalgudi", "name": "lalgudi" },
        { "value": "Shrirangapattana", "name": "shrirangapattana" },
        { "value": "Niwari", "name": "niwari" },
        { "value": "Natham", "name": "natham" },
        { "value": "Unnamalaikadai", "name": "unnamalaikadai" },
        { "value": "PurqUrban Agglomerationzi", "name": "purqurbanagglomerationzi" },
        { "value": "Shamsabad, Farrukhabad", "name": "shamsabad,farrukhabad" },
        { "value": "Mirganj", "name": "mirganj" },
        { "value": "Todaraisingh", "name": "todaraisingh" },
        { "value": "Warhapur", "name": "warhapur" },
        { "value": "Rajam", "name": "rajam" },
        { "value": "Urmar Tanda", "name": "urmartanda" },
        { "value": "Lonar", "name": "lonar" },
        { "value": "Powayan", "name": "powayan" },
        { "value": "P.N.Patti", "name": "p.n.patti" },
        { "value": "Palampur", "name": "palampur" },
        {
          "value": "Srisailam Project (Right Flank Colony) Township",
          "name": "srisailamproject (right flank colony) township"
        },
        { "value": "Sindagi", "name": "sindagi" },
        { "value": "Sandi", "name": "sandi" },
        { "value": "Vaikom", "name": "vaikom" },
        { "value": "Malda", "name": "malda" },
        { "value": "Tharangambadi", "name": "tharangambadi" },
        { "value": "Sakaleshapura", "name": "sakaleshapura" },
        { "value": "Lalganj", "name": "lalganj" },
        { "value": "Malkangiri", "name": "malkangiri" },
        { "value": "Rapar", "name": "rapar" },
        { "value": "Mauganj", "name": "mauganj" },
        { "value": "Todabhim", "name": "todabhim" },
        { "value": "Srinivaspur", "name": "srinivaspur" },
        { "value": "Murliganj", "name": "murliganj" },
        { "value": "Reengus", "name": "reengus" },
        { "value": "Sawantwadi", "name": "sawantwadi" },
        { "value": "Tittakudi", "name": "tittakudi" },
        { "value": "Lilong", "name": "lilong" },
        { "value": "Rajaldesar", "name": "rajaldesar" },
        { "value": "Pathardi", "name": "pathardi" },
        { "value": "Achhnera", "name": "achhnera" },
        { "value": "Pacode", "name": "pacode" },
        { "value": "Naraura", "name": "naraura" },
        { "value": "Nakur", "name": "nakur" },
        { "value": "Palai", "name": "palai" },
        { "value": "Morinda, India", "name": "morinda,india" },
        { "value": "Manasa", "name": "manasa" },
        { "value": "Nainpur", "name": "nainpur" },
        { "value": "Sahaspur", "name": "sahaspur" },
        { "value": "Pauni", "name": "pauni" },
        { "value": "Prithvipur", "name": "prithvipur" },
        { "value": "Ramtek", "name": "ramtek" },
        { "value": "Silapathar", "name": "silapathar" },
        { "value": "Songadh", "name": "songadh" },
        { "value": "Safipur", "name": "safipur" },
        { "value": "Sohagpur", "name": "sohagpur" },
        { "value": "Mul", "name": "mul" },
        { "value": "Sadulshahar", "name": "sadulshahar" },
        { "value": "Phillaur", "name": "phillaur" },
        { "value": "Sambhar", "name": "sambhar" },
        { "value": "Prantij", "name": "prantij" },
        { "value": "Nagla", "name": "nagla" },
        { "value": "Pattran", "name": "pattran" },
        { "value": "Mount Abu", "name": "mountabu" },
        { "value": "Reoti", "name": "reoti" },
        { "value": "Tenu dam-cum-Kathhara", "name": "tenudam-cum-kathhara" },
        { "value": "Panchla", "name": "panchla" },
        { "value": "Sitarganj", "name": "sitarganj" },
        { "value": "Pasighat", "name": "pasighat" },
        { "value": "Motipur", "name": "motipur" },
        { "value": "O' Valley", "name": "o'valley" },
        { "value": "Raghunathpur", "name": "raghunathpur" },
        { "value": "Suriyampalayam", "name": "suriyampalayam" },
        { "value": "Qadian", "name": "qadian" },
        { "value": "Rairangpur", "name": "rairangpur" },
        { "value": "Silvassa", "name": "silvassa" },
        { "value": "Nowrozabad (Khodargama)", "name": "nowrozabad(khodargama)" },
        { "value": "Mangrol", "name": "mangrol" },
        { "value": "Soyagaon", "name": "soyagaon" },
        { "value": "Sujanpur", "name": "sujanpur" },
        { "value": "Manihari", "name": "manihari" },
        { "value": "Sikanderpur", "name": "sikanderpur" },
        { "value": "Mangalvedhe", "name": "mangalvedhe" },
        { "value": "Phulera", "name": "phulera" },
        { "value": "Ron", "name": "ron" },
        { "value": "Sholavandan", "name": "sholavandan" },
        { "value": "Saidpur", "name": "saidpur" },
        { "value": "Shamgarh", "name": "shamgarh" },
        { "value": "Thammampatti", "name": "thammampatti" },
        { "value": "Maharajpur", "name": "maharajpur" },
        { "value": "Multai", "name": "multai" },
        { "value": "Mukerian", "name": "mukerian" },
        { "value": "Sirsi", "name": "sirsi" },
        { "value": "Purwa", "name": "purwa" },
        { "value": "Sheohar", "name": "sheohar" },
        { "value": "Namagiripettai", "name": "namagiripettai" },
        { "value": "Parasi", "name": "parasi" },
        { "value": "Lathi", "name": "lathi" },
        { "value": "Lalganj", "name": "lalganj" },
        { "value": "Narkhed", "name": "narkhed" },
        { "value": "Mathabhanga", "name": "mathabhanga" },
        { "value": "Shendurjana", "name": "shendurjana" },
        { "value": "Peravurani", "name": "peravurani" },
        { "value": "Mariani", "name": "mariani" },
        { "value": "Phulpur", "name": "phulpur" },
        { "value": "Rania", "name": "rania" },
        { "value": "Pali", "name": "pali" },
        { "value": "Pachore", "name": "pachore" },
        { "value": "Parangipettai", "name": "parangipettai" },
        { "value": "Pudupattinam", "name": "pudupattinam" },
        { "value": "Panniyannur", "name": "panniyannur" },
        { "value": "Maharajganj", "name": "maharajganj" },
        { "value": "Rau", "name": "rau" },
        { "value": "Monoharpur", "name": "monoharpur" },
        { "value": "Mandawa", "name": "mandawa" },
        { "value": "Marigaon", "name": "marigaon" },
        { "value": "Pallikonda", "name": "pallikonda" },
        { "value": "Pindwara", "name": "pindwara" },
        { "value": "Shishgarh", "name": "shishgarh" },
        { "value": "Patur", "name": "patur" },
        { "value": "Mayang Imphal", "name": "mayangimphal" },
        { "value": "Mhowgaon", "name": "mhowgaon" },
        { "value": "Guruvayoor", "name": "guruvayoor" },
        { "value": "Mhaswad", "name": "mhaswad" },
        { "value": "Sahawar", "name": "sahawar" },
        { "value": "Sivagiri", "name": "sivagiri" },
        { "value": "Mundargi", "name": "mundargi" },
        { "value": "Punjaipugalur", "name": "punjaipugalur" },
        { "value": "Kailasahar", "name": "kailasahar" },
        { "value": "Samthar", "name": "samthar" },
        { "value": "Sakti", "name": "sakti" },
        { "value": "Sadalagi", "name": "sadalagi" },
        { "value": "Silao", "name": "silao" },
        { "value": "Mandalgarh", "name": "mandalgarh" },
        { "value": "Loha", "name": "loha" },
        { "value": "Pukhrayan", "name": "pukhrayan" },
        { "value": "Padmanabhapuram", "name": "padmanabhapuram" },
        { "value": "Belonia", "name": "belonia" },
        { "value": "Saiha", "name": "saiha" },
        { "value": "Srirampore", "name": "srirampore" },
        { "value": "Talwara", "name": "talwara" },
        { "value": "Puthuppally", "name": "puthuppally" },
        { "value": "Khowai", "name": "khowai" },
        { "value": "Vijaypur", "name": "vijaypur" },
        { "value": "Takhatgarh", "name": "takhatgarh" },
        { "value": "Thirupuvanam", "name": "thirupuvanam" },
        { "value": "Adra", "name": "adra" },
        { "value": "Piriyapatna", "name": "piriyapatna" },
        { "value": "Obra", "name": "obra" },
        { "value": "Adalaj", "name": "adalaj" },
        { "value": "Nandgaon", "name": "nandgaon" },
        { "value": "Barh", "name": "barh" },
        { "value": "Chhapra", "name": "chhapra" },
        { "value": "Panamattom", "name": "panamattom" },
        { "value": "Niwai", "name": "niwai" },
        { "value": "Bageshwar", "name": "bageshwar" },
        { "value": "Tarbha", "name": "tarbha" },
        { "value": "Adyar", "name": "adyar" },
        { "value": "Narsinghgarh", "name": "narsinghgarh" },
        { "value": "Warud", "name": "warud" },
        { "value": "Asarganj", "name": "asarganj" },
        { "value": "Sarsod", "name": "sarsod" },
        { "value": "Gandhinagar", "name": "gandhinagar" },
        { "value": "Kullu", "name": "kullu" },
        { "value": "Manali", "name": "manali" },
        { "value": "Mirzapur", "name": "mirzapur" },
        { "value": "Kota", "name": "kota" },
        { "value": "Dispur", "name": "dispur" }
      ]
          },

    {
      type: "text",
      title: "Address",
      name: "franchise_address",
      values: "",
      class: "col-span-6",
      require: true,
    },
    {
      type: "hidden",
      title: "Status",
      name: "status",
      values: 1,
      class: "col-span-3",
      require: false,
    },
    {
      type: "hidden",
      title: "Date",
      name: "created_at",
      values: new Date(),
      class: "col-span-3",
      require: false,
    },
  ], user: [
    {
      type: "text",
      title: "Name",
      name: "name",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Phone",
      name: "phone",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "Email",
      name: "email",
      values: "",
      class: "col-span-3",
      require: true,
    },
    {
      type: "text",
      title: "User Name",
      name: "username",
      values: "",
      class: "col-span-3",
      require: true,
    } ,{
      type: "text",
      title: "Address",
      name: "franchise_address",
      values: "",
      class: "col-span-6",
      require: true,
    },
    {
      type: "hidden",
      title: "Status",
      name: "status",
      values: 1,
      class: "col-span-3",
      require: false,
    },
    {
      type: "hidden",
      title: "Date",
      name: "created_at",
      values: new Date(),
      class: "col-span-3",
      require: false,
    }]
};
